### ISSUE TITLE
Running Error: KeyError: 'input_text'

### ISSUE THREAD

**Issue by lilianoa** [muzairkhattak/ProText#2]
Thanks for sharing the paper and code. It is a great work!
When I run the code and receive an error message:
 File "D:\ProText-main\trainers\protext.py", line 295, in parse_batch_train
    input = batch["input_text"]
KeyError: 'input_text'
Could you help me? Thanks.

**Comment by muzairkhattak** [comment]
Dear @lilianoa,

Thank you for showing interest in ProText! 

Regarding your query, I think there might be an issue with installing the Dassl Library. 
Kindly note that we have used our own custom Dassl Library for the ProText framework. Can you confirm if you have installed the Dassl library[ from our local folder? ](https://github.com/muzairkhattak/ProText/tree/main/Dassl.pytorch)

You can install it using the steps mentioned in the [INSTALL.md](https://github.com/muzairkhattak/ProText/blob/main/docs/INSTALL.md).

I hope that is helpful. 
Thank you and kind regards!

**Comment by muzairkhattak** [comment]
Hi @lilianoa,

I hope your issue has been resolved. 
Feel free to reopen the issue in case there are still any issues. 

Thank you and kind regards!
