### ISSUE TITLE
Timm model

### ISSUE THREAD

**Issue by TahaKoleilat** [muzairkhattak/ProText#4]
How to perform this method on a timm clip model? What should be changed so that the code works?

**Comment by muzairkhattak** [comment]
Hi @TahaKoleilat,

Can you clarify if you need to use timm clip model just for the inference? or you also required to perform training?

For the inference, you will need to replace the clip model instantiations with the timm models in the [protext.py](https://github.com/muzairkhattak/ProText/blob/main/trainers/protext.py). 

Let me know if you have any confusion! Thank you!

**Comment by muzairkhattak** [comment]
Hi @TahaKoleilat,

I am closing this issue for now. Feel free to reopen if you still have any question.

Thank you and kind regards!
