### ISSUE TITLE
Doubts about variables in the __getitem__ function of the DatasetWrapper_TextOnly ClassC

### ISSUE THREAD

**Issue by HUOUO7** [muzairkhattak/ProText#8]
### Excuse me, I would like to ask whether the two variables in the two lines of code in this block are written incorrectly, and whether they should be switched up and down？https://github.com/muzairkhattak/ProText/blob/c779baa95d63617e0006464a6fb94fa3fa13a217/Dassl.pytorch/dassl/data/data_manager.py#L365-L366

**Comment by muzairkhattak** [comment]
Hi @HUOUO7,

Thank you for showing interest in ProText! 

Regarding your question, kindly note that the variable values are propagated correctly as we expect. There is just a flipped naming convention of the variable name, which you can ignore. 

In each text-only training example, our input is a fixed template (e.g., a photo of a CLS) that is correctly stored in `single_input_text`, and our output is an LLM description of the same CLS, which is present in `single_input_label`.

During training, ProText maximizes the transformation/distillation from fixed template sentences to LLM generated sentences of the same class.

I hope this is helpful.
Please let me know if you have any additional queries.

Thank you and kind regards!
